on: push
name: Licensed CI
jobs:
  updateLicense:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: jonabc/setup-licensed@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version: 2.x
    - run: npm install # install your projects dependencies in local environment
    - id: licensed
      uses: jonabc/licensed-ci@v1.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/github-script@0.2.0
      if: always() && steps.licensed.outputs.pr_number
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            ...context.repo,
            issue_number: ${{ steps.licensed.outputs.pr_number }}
            body: 'Update License'
          })
